services:
  identifier:
    restart: "no"
    ports:
      - "80:80"
  dispatcher:
    restart: "no"
  frontend:
    restart: "no"
  resource:
    restart: "no"
  cache:
    restart: "no"
  database:
    restart: "no"
  triplestore:
    environment:
      ENABLE_CORS: "true"
    ports:
      - 8890:8890
    restart: "no"
  delta-notifier:
    restart: "no"
  migrations:
    restart: "no"
    volumes:
      - ./config/development/migrations:/data/migrations/dev
  login:
    restart: "no"
  registration:
    restart: "no"
  entity-mapping:
    environment:
      MODE: "development"
      LOG_LEVEL: "debug"
    ports:
      - "8888:80"
    restart: "no"
  yasgui:
    image: erikap/yasgui
    ports:
      - "8891:80"
    environment:
      ENABLE_ENDPOINT_SELECTOR: "true"
      DEFAULT_SPARQL_ENDPOINT: "http://localhost:8890/sparql"
    restart: "no"      
  # spex:
  #   # Needs some more build instructions
  #   image: spex
  #   ports:
  #     - "8892:80"
  #   environment:
  #     ENABLE_ENDPOINT_SELECTOR: "true"
  #     DEFAULT_SPARQL_ENDPOINT: "http://localhost:8890/sparql"
  #     restart: "no"



