services:
  virtuoso:
    environment:
      ENABLE_CORS: "true"
    ports:
      - 8890:8890
  yasgui:
    image: erikap/yasgui
    ports:
      - "8891:80"
    environment:
      ENABLE_ENDPOINT_SELECTOR: "true"
      DEFAULT_SPARQL_ENDPOINT: "http://localhost:8890/sparql"
  spex:
    image: spex
    ports:
      - "8892:80"
    environment:
      ENABLE_ENDPOINT_SELECTOR: "true"
      DEFAULT_SPARQL_ENDPOINT: "http://localhost:8890/sparql"
  entity-mapping:
    environment:
      MODE: "development"
      LOG_LEVEL: "debug"
    ports:
      - "8888:80"
