services:
  identifier:
    image: semtech/mu-identifier:1.10.3
    environment:
      SESSION_COOKIE_SECURE: "on"
    links:
      - dispatcher:dispatcher
    labels:
      - "logging=true"
    restart: always
  dispatcher:
    image: semtech/mu-dispatcher:2.1.0-beta.2
    links:
      - resource:resource
    volumes:
      - ./config/dispatcher:/config
    labels:
      - "logging=true"
    restart: always
  frontend:
    image: redpencil/frontend-poc-publiq-entity-resolution:latest # todo: use specific tagged frontend
    labels:
      - "logging=true"
    restart: always
  resource:
    image: semtech/mu-cl-resources:1.25.0
    links:
      - database:database
    volumes:
      - ./config/resources:/config
    environment:
      CACHE_CLEAR_PATH: "http://cache/.mu/clear-keys"
    labels:
      - "logging=true"
    restart: always
  cache:
    image: semtech/mu-cache:2.0.2
    links:
      - resource:backend
    labels:
      - "logging=true"
    restart: always
  database:
    image: semtech/sparql-parser:0.0.13
    volumes:
      - ./config/authorization:/config
      - ./data/authorization:/data
    labels:
      - "logging=true"
    restart: always
  triplestore:
    image: redpencil/virtuoso:1.3.0-rc.1
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    volumes:
      - ./data/db:/data
      - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini
      - ./config/virtuoso/toLoad:/data/toLoad
    labels:
      - "logging=true"
    restart: always
  deltanotifier:
    image: semtech/mu-delta-notifier:0.4.0
    volumes:
        - ./config/delta:/config
    labels:
      - "logging=true"
    restart: always
  migrations:
    # Publiq data loaded through Virtuoso toLoad because of its size
    image: semtech/mu-migrations-service:0.9.0
    environment:
      MU_SPARQL_ENDPOINT: "http://triplestore:8890/sparql"
    volumes:
      - ./config/migrations:/data/migrations
    labels:
      - "logging=true"
    restart: always
  login:
    image: semtech/mu-login-service:3.0.0
    environment:
      USERS_GRAPH: "http://mu.semte.ch/graphs/users"
      SESSIONS_GRAPH: "http://mu.semte.ch/graphs/sessions"
    links:
      - database:database
    labels:
      - "logging=true"
    restart: always
  registration:
    image: semtech/mu-registration-service:2.7.3
    entrypoint: echo "Only needed for mu script"
    environment:
      USERS_GRAPH: "http://mu.semte.ch/graphs/users"
      SESSIONS_GRAPH: "http://mu.semte.ch/graphs/sessions"
    links:
      - database:database
    labels:
      - "logging=true"
    restart: "no"
  entity-mapping:
    image: redpencil/publiq-entity-mapping-service:latest
    environment:
      WORKERS: "1"
      MU_SPARQL_ENDPOINT: "http://triplestore:8890/sparql"
      MU_SPARQL_UPDATEPOINT: "http://triplestore:8890/sparql"
    labels:
      - "logging=true"
    restart: always
