services:
  virtuoso:
    image: redpencil/virtuoso:1.3.0-rc.1
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
      ENABLE_CORS: "true"
    volumes:
      - ./data/db:/data
      - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini
      - ./config/virtuoso/toLoad:/data/toLoad
    ports:
      - 8890:8890
  migrations:
    # Publiq data loaded through Virtuoso toLoad because of its size
    image: semtech/mu-migrations-service:0.9.0
    environment:
      MU_SPARQL_ENDPOINT: "http://virtuoso:8890/sparql"
    volumes:
      - ./config/migrations:/data/migrations
  yasgui:
    image: erikap/yasgui
    ports:
      - "8891:80"
    environment:
      ENABLE_ENDPOINT_SELECTOR: "true"
      DEFAULT_SPARQL_ENDPOINT: "http://localhost:8890/sparql"
  spex:
    image: spex
    ports:
      - "8892:80"
    environment:
      ENABLE_ENDPOINT_SELECTOR: "true"
      DEFAULT_SPARQL_ENDPOINT: "http://localhost:8890/sparql"
  # database:
  #   image: semtech/mu-authorization:0.6.0-beta.5
  #   environment:
  #     MU_SPARQL_ENDPOINT: "http://virtuoso:8890/sparql"
  #   volumes:
  #     - ./config/authorization:/config
  entity-mapping:
    build: /home/michael/rpio/projects/PUB-entity-resolution/repos/entity-mapping-service
    environment:
      MODE: "development"
      LOG_LEVEL: "debug"
      WORKERS: "1"
      MU_SPARQL_ENDPOINT: "http://virtuoso:8890/sparql"
      MU_SPARQL_UPDATEPOINT: "http://virtuoso:8890/sparql"
    ports:
      - "8888:80"
    volumes:
      - /home/michael/rpio/projects/PUB-entity-resolution/repos/entity-mapping-service:/app
