PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX people: <http://ext.data.gift/people/>
PREFIX accounts: <http://ext.data.gift/accounts/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX mu:      <http://mu.semte.ch/vocabularies/core/>
PREFIX account: <http://mu.semte.ch/vocabularies/account/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

INSERT DATA {
   GRAPH <http://mu.semte.ch/graphs/users> {
     people:fdf8771e-030a-4d20-ba30-f53b32fc1e63 a foaf:Person ;
                   foaf:name "admin" ;
                   foaf:account accounts:b75e32da-e743-4440-812f-ff03b726342c ;
                   mu:uuid "fdf8771e-030a-4d20-ba30-f53b32fc1e63" ;
                   dcterms:created "2025-01-02T14:12:57+00:00"^^xsd:dateTime ;
                   dcterms:modified "2025-01-02T14:12:57+00:00"^^xsd:dateTime .
     accounts:b75e32da-e743-4440-812f-ff03b726342c a foaf:OnlineAccount ;
                   foaf:accountName "admin" ;
                   mu:uuid "b75e32da-e743-4440-812f-ff03b726342c" ;
                   account:password """$2a$12$Ny/TjurYlLI8FLez3vFRluzbDT/hqqIa.NAygQQUzanMKwAjNJ8j2""" ;
                   account:salt "919bddec4df6d11d1de4e2bee2b6fd60" ;
                   account:status <http://mu.semte.ch/vocabularies/account/status/active> ;
                   dcterms:created "2025-01-02T14:12:57+00:00"^^xsd:dateTime ;
                   dcterms:modified "2025-01-02T14:12:57+00:00"^^xsd:dateTime .
    }
}