PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX locn: <http://www.w3.org/ns/locn#>

SELECT count(?address)
WHERE {
    {
        SELECT DISTINCT ?address ?adminunitl1 ?postcode ?postname ?thoroughfare ?locator_designator
        WHERE {
            VALUES ?g {
                <http://locatieslinkeddata.ticketgang-locations.ticketing.acagroup.be>
                <http://locatiessparql.kunstenpunt-locaties.professionelekunsten.kunsten.be>
                <http://metadata.cultuurparticipatie-metadata.vrijetijdsparticipatie.publiq.be>
                <http://placessparql.publiq-uit-locaties.vrijetijdsparticipatie.publiq.be>
                <http://organisatorensparql.publiq-uit-organisatoren.vrijetijdsparticipatie.publiq.be>
            }
            GRAPH ?g {
                ?address a locn:Address .
                ?address (locn:postcode | locn:postCode) ?postcode .
                ?address locn:postName ?postname FILTER(LANG(?postname) = "nl" ).
                ?address locn:thoroughfare ?thoroughfare FILTER(LANG(?thoroughfare) = "nl" ).
                ?address locn:locatorDesignator ?locator_designator .
                ?address locn:adminUnitL1 ?adminunitl1 .
            }
            FILTER NOT EXISTS { ?address ^locn:address/prov:invalidatedAtTime ?time . }
        }
        ORDER BY ?postcode
    }
}
